// <auto-generated />
using System;
using FridgeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FridgeManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501074644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FridgeManagement.Models.BusinessInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BusinessInfos");
                });

            modelBuilder.Entity("FridgeManagement.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            ContactPerson = "John Doe",
                            Email = "spazaA@example.com",
                            Name = "Spaza Shop A",
                            PhoneNumber = "0123456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            ContactPerson = "Jane Smith",
                            Email = "shebeenB@example.com",
                            Name = "Shebeen B",
                            PhoneNumber = "0987654321",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.DeliveryNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityDelivered")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("DeliveryNotes");
                });

            modelBuilder.Entity("FridgeManagement.Models.FaultReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedTechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiagnosisNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportedByCustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledRepairDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTechnicianId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ReportedByCustomerId");

                    b.ToTable("FaultReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTechnicianId = 5,
                            Description = "Fridge not cooling properly",
                            FridgeId = 1,
                            IsDeleted = false,
                            Priority = "High",
                            ReportedByCustomerId = 1,
                            ReportedDate = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Strange noise from compressor",
                            FridgeId = 2,
                            IsDeleted = false,
                            Priority = "Medium",
                            ReportedByCustomerId = 2,
                            ReportedDate = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Reported"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.Fridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Frosty",
                            Model = "Cooler X100",
                            PurchaseDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "FRIDGE-001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "IceCold",
                            Model = "ChillMaster 500",
                            PurchaseDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "FRIDGE-002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Frosty",
                            Model = "Cooler X100",
                            SerialNumber = "FRIDGE-003",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.FridgeAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FridgeId");

                    b.ToTable("FridgeAllocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllocationDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            FridgeId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            AllocationDate = new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            FridgeId = 2,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.FridgeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("FridgeRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            IsDeleted = false,
                            QuantityRequested = 2,
                            Reason = "Need additional fridge for new stock",
                            RequestDate = new DateTime(2025, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            AdminNotes = "Will deliver next week",
                            CustomerId = 2,
                            IsDeleted = false,
                            QuantityRequested = 1,
                            Reason = "Current fridge is too small",
                            RequestDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Industrial Rd",
                            City = "Johannesburg",
                            Name = "Main Warehouse",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Harbour St",
                            City = "Cape Town",
                            Name = "Cape Town Depot",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecklistResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaintenanceScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceScheduleId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("FridgeManagement.Models.MaintenanceSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedTechnicianId")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTechnicianId");

                    b.HasIndex("FridgeId");

                    b.ToTable("MaintenanceSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTechnicianId = 6,
                            FridgeId = 1,
                            IsDeleted = false,
                            Notes = "Quarterly maintenance",
                            ScheduledDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTechnicianId = 6,
                            FridgeId = 2,
                            IsDeleted = false,
                            Notes = "Check cooling efficiency",
                            ScheduledDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuotationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("FridgeManagement.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.ToTable("PurchaseRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuantityRequested = 5,
                            Reason = "Low stock of Cooler X100",
                            RequestDate = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedById = 3,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            QuantityRequested = 10,
                            Reason = "Need additional fridges for new customers",
                            RequestDate = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedById = 3,
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstimatedDeliveryDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RFQId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("FridgeManagement.Models.RFQSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RFQId");

                    b.HasIndex("SupplierId");

                    b.ToTable("RFQSuppliers");
                });

            modelBuilder.Entity("FridgeManagement.Models.RememberedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RememberedDevices");
                });

            modelBuilder.Entity("FridgeManagement.Models.RequestForQuotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PurchaseRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequestId");

                    b.ToTable("RequestForQuotations");
                });

            modelBuilder.Entity("FridgeManagement.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("FridgeManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPinExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@fridge.com",
                            FailedLoginAttempts = 0,
                            Gender = "Male",
                            IsTwoFactorEnabled = false,
                            Name = "System",
                            PasswordHash = "admin123",
                            PhoneNumber = "",
                            Role = "ADMINISTRATOR",
                            Status = "Active",
                            Surname = "Administrator",
                            Title = "Mr",
                            Username = "admin@fridge.com"
                        },
                        new
                        {
                            Id = 2,
                            Email = "customer.liaison@fridge.com",
                            FailedLoginAttempts = 0,
                            Gender = "Female",
                            IsTwoFactorEnabled = false,
                            Name = "Alice",
                            PasswordHash = "liaison123",
                            PhoneNumber = "",
                            Role = "CUSTOMERLIAISON",
                            Status = "Active",
                            Surname = "Johnson",
                            Title = "Ms",
                            Username = "customer.liaison@fridge.com"
                        },
                        new
                        {
                            Id = 3,
                            Email = "inventory.liaison@fridge.com",
                            FailedLoginAttempts = 0,
                            Gender = "Male",
                            IsTwoFactorEnabled = false,
                            Name = "Bob",
                            PasswordHash = "inventory123",
                            PhoneNumber = "",
                            Role = "INVENTORYLIAISON",
                            Status = "Active",
                            Surname = "Smith",
                            Title = "Mr",
                            Username = "inventory.liaison@fridge.com"
                        },
                        new
                        {
                            Id = 4,
                            Email = "customer@spaza.com",
                            FailedLoginAttempts = 0,
                            Gender = "Male",
                            IsTwoFactorEnabled = false,
                            Name = "Spaza",
                            PasswordHash = "customer123",
                            PhoneNumber = "",
                            Role = "CUSTOMER",
                            Status = "Active",
                            Surname = "Owner",
                            Title = "Mr",
                            Username = "customer@spaza.com"
                        },
                        new
                        {
                            Id = 5,
                            Email = "fault.tech@fridge.com",
                            FailedLoginAttempts = 0,
                            Gender = "Male",
                            IsTwoFactorEnabled = false,
                            Name = "Charlie",
                            PasswordHash = "tech123",
                            PhoneNumber = "",
                            Role = "FAULTTECHNICIAN",
                            Status = "Active",
                            Surname = "Brown",
                            Title = "Mr",
                            Username = "fault.tech@fridge.com"
                        },
                        new
                        {
                            Id = 6,
                            Email = "maint.tech@fridge.com",
                            FailedLoginAttempts = 0,
                            Gender = "Female",
                            IsTwoFactorEnabled = false,
                            Name = "Diana",
                            PasswordHash = "maint123",
                            PhoneNumber = "",
                            Role = "MAINTENANCETECHNICIAN",
                            Status = "Active",
                            Surname = "Prince",
                            Title = "Ms",
                            Username = "maint.tech@fridge.com"
                        },
                        new
                        {
                            Id = 7,
                            Email = "purchasing@fridge.com",
                            FailedLoginAttempts = 0,
                            Gender = "Female",
                            IsTwoFactorEnabled = false,
                            Name = "Eve",
                            PasswordHash = "purchase123",
                            PhoneNumber = "",
                            Role = "PURCHASINGMANAGER",
                            Status = "Active",
                            Surname = "Adams",
                            Title = "Ms",
                            Username = "purchasing@fridge.com"
                        },
                        new
                        {
                            Id = 8,
                            Email = "supplier@coolers.com",
                            FailedLoginAttempts = 0,
                            Gender = "Male",
                            IsTwoFactorEnabled = false,
                            Name = "Cooler",
                            PasswordHash = "supplier123",
                            PhoneNumber = "",
                            Role = "SUPPLIER",
                            Status = "Active",
                            Surname = "Supplier",
                            Title = "Mr",
                            Username = "supplier@coolers.com"
                        });
                });

            modelBuilder.Entity("FridgeManagement.Models.DeliveryNote", b =>
                {
                    b.HasOne("FridgeManagement.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("FridgeManagement.Models.FaultReport", b =>
                {
                    b.HasOne("FridgeManagement.Models.User", "AssignedTechnician")
                        .WithMany()
                        .HasForeignKey("AssignedTechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FridgeManagement.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeManagement.Models.Customer", "ReportedByCustomer")
                        .WithMany()
                        .HasForeignKey("ReportedByCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTechnician");

                    b.Navigation("Fridge");

                    b.Navigation("ReportedByCustomer");
                });

            modelBuilder.Entity("FridgeManagement.Models.FridgeAllocation", b =>
                {
                    b.HasOne("FridgeManagement.Models.Customer", "Customer")
                        .WithMany("FridgeAllocations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeManagement.Models.Fridge", "Fridge")
                        .WithMany("FridgeAllocations")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Fridge");
                });

            modelBuilder.Entity("FridgeManagement.Models.FridgeRequest", b =>
                {
                    b.HasOne("FridgeManagement.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FridgeManagement.Models.MaintenanceLog", b =>
                {
                    b.HasOne("FridgeManagement.Models.MaintenanceSchedule", "MaintenanceSchedule")
                        .WithMany()
                        .HasForeignKey("MaintenanceScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeManagement.Models.User", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceSchedule");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FridgeManagement.Models.MaintenanceSchedule", b =>
                {
                    b.HasOne("FridgeManagement.Models.User", "AssignedTechnician")
                        .WithMany()
                        .HasForeignKey("AssignedTechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeManagement.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTechnician");

                    b.Navigation("Fridge");
                });

            modelBuilder.Entity("FridgeManagement.Models.PurchaseOrder", b =>
                {
                    b.HasOne("FridgeManagement.Models.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("FridgeManagement.Models.PurchaseRequest", b =>
                {
                    b.HasOne("FridgeManagement.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("FridgeManagement.Models.Quotation", b =>
                {
                    b.HasOne("FridgeManagement.Models.RequestForQuotation", "RFQ")
                        .WithMany()
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeManagement.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RFQ");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FridgeManagement.Models.RFQSupplier", b =>
                {
                    b.HasOne("FridgeManagement.Models.RequestForQuotation", "RFQ")
                        .WithMany()
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FridgeManagement.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RFQ");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FridgeManagement.Models.RememberedDevice", b =>
                {
                    b.HasOne("FridgeManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FridgeManagement.Models.RequestForQuotation", b =>
                {
                    b.HasOne("FridgeManagement.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany()
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("FridgeManagement.Models.Customer", b =>
                {
                    b.Navigation("FridgeAllocations");
                });

            modelBuilder.Entity("FridgeManagement.Models.Fridge", b =>
                {
                    b.Navigation("FridgeAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
